// Build assets/map-data.js from Natural Earth 10m land + VATSIM FIR boundaries.
// World units: Mercator, S px per radian, origin at (LON0, LAT0) = Taiwan centre.
// Usage: node tools/build-map.mjs <land.geojson> <Boundaries.geojson> <out.js>
import fs from "node:fs";
const [landPath, firPath, outPath] = process.argv.slice(2);
const S = 1900, LON0 = 121, LAT0 = 23.7;
const rad = Math.PI / 180;
const my = (lat) => Math.log(Math.tan(Math.PI / 4 + (lat * rad) / 2));
const Y0 = my(LAT0);
const proj = ([lon, lat]) => [S * (lon - LON0) * rad, -S * (my(lat) - Y0)];

function rdp(pts, eps) {
  if (pts.length < 3) return pts;
  const keep = new Uint8Array(pts.length); keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop(); const [ax, ay] = pts[a], [bx, by] = pts[b];
    const dx = bx - ax, dy = by - ay, L = Math.hypot(dx, dy) || 1e-9;
    let md = -1, mi = -1;
    for (let i = a + 1; i < b; i++) {
      const d = Math.abs(dy * pts[i][0] - dx * pts[i][1] + bx * ay - by * ax) / L;
      if (d > md) { md = d; mi = i; }
    }
    if (md > eps) { keep[mi] = 1; stack.push([a, mi], [mi, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}
const area = (r) => { let s = 0; for (let i = 0; i < r.length; i++) { const [x1, y1] = r[i], [x2, y2] = r[(i + 1) % r.length]; s += x1 * y2 - x2 * y1; } return Math.abs(s / 2); };
const f1 = (v) => (Math.round(v * 10) / 10).toString();
function ringsToPath(rings, eps, minArea, close = true) {
  let d = "", n = 0;
  for (const ring of rings) {
    const q = ring.map(proj);
    let p;
    if (close && q.length > 4) { // closed ring: simplify two halves so RDP has a real baseline
      const h = Math.floor(q.length / 2);
      p = rdp(q.slice(0, h + 1), eps).concat(rdp(q.slice(h), eps).slice(1));
    } else p = rdp(q, eps);
    if (close && (p.length < 4 || area(p) < minArea)) continue;
    d += "M" + p.map(([x, y]) => f1(x) + " " + f1(y)).join("L") + (close ? "Z" : "");
    n += p.length;
  }
  return { d, n };
}
const land = JSON.parse(fs.readFileSync(landPath, "utf8"));
const rings = [];
for (const f of land.features) {
  const g = f.geometry; if (!g) continue;
  const polys = g.type === "Polygon" ? [g.coordinates] : g.type === "MultiPolygon" ? g.coordinates : [];
  for (const poly of polys) for (const r of poly) rings.push(r);
}
const landP = ringsToPath(rings, 0.09, 0.6);
// Taiwan (main island + Penghu + Green/Orchid islands) as its own path for highlighting
const inTW = (r) => r.every(([lo, la]) => lo > 119.2 && lo < 122.2 && la > 21.7 && la < 25.45);
const twP = ringsToPath(rings.filter(inTW), 0.04, 0.02);

const firs = JSON.parse(fs.readFileSync(firPath, "utf8"));
const firIds = ["RCAA"];
const firOut = {};
for (const f of firs.features) {
  const id = f.properties.id; if (!firIds.includes(id) || firOut[id]) continue;
  const g = f.geometry; const polys = g.type === "Polygon" ? [g.coordinates] : g.coordinates;
  const rs = []; for (const poly of polys) for (const r of poly) rs.push(r);
  firOut[id] = { d: ringsToPath(rs, 0.05, 0).d, label: [+f.properties.label_lon, +f.properties.label_lat] };
}
// graticule every 5 degrees
let grat = "";
for (let lon = 90; lon <= 160; lon += 5) { const pts = []; for (let lat = -5; lat <= 50; lat += 1) pts.push(proj([lon, lat])); grat += "M" + pts.map(([x, y]) => f1(x) + " " + f1(y)).join("L"); }
for (let lat = 0; lat <= 50; lat += 5) { const pts = []; for (let lon = 88; lon <= 160; lon += 1) pts.push(proj([lon, lat])); grat += "M" + pts.map(([x, y]) => f1(x) + " " + f1(y)).join("L"); }

const out = `// Generated by tools/build-map.mjs — do not edit by hand.
// Sources: Natural Earth 10m land + minor islands (public domain); FIR outlines: VATSIM vatspy-data-project (illustrative).
// Projection: Mercator, ${S}px/rad, origin lon ${LON0} / lat ${LAT0}. Use ATFM_MAP.project([lon,lat]) for world coords.
(function(){
var S=${S},LON0=${LON0},LAT0=${LAT0},R=Math.PI/180;
function my(l){return Math.log(Math.tan(Math.PI/4+l*R/2));}
var Y0=my(LAT0);
window.ATFM_MAP={
  project:function(p){return [S*(p[0]-LON0)*R,-S*(my(p[1])-Y0)];},
  land:${JSON.stringify(landP.d)},
  taiwan:${JSON.stringify(twP.d)},
  graticule:${JSON.stringify(grat)},
  fir:${JSON.stringify(firOut)}
};
})();
`;
fs.writeFileSync(outPath, out);
console.log("land points", landP.n, "bytes", out.length, "firs", Object.keys(firOut));
